/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pacientes.java
 *
 * Created on 14/08/2011, 17:18:16
 */
package janelasdepesquisas;

import DAO.PacienteDAO;
import ProcessosBD.*;
import janelasConsultaSimilaridade.JanelaCasoFichaMedica;
import janelasConsultaSimilaridade.ReferenciasSimilaridade;
import janelasdoprojetao.Cadastro.JanelaCadastroPaciente;
import janelasdoprojetao.JanelaPrincipal;
import janelasdoprojetao.PacientePorPaciente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Glaupe e Iris
 */
public class Pacientes extends javax.swing.JPanel {

    /** Creates new form Pacientes */
    ArrayList<Paciente> lista = null;
    public Pacientes() {
        initComponents();
        
        PacienteDAO dao = new PacienteDAO();
        
        lista = dao.selectMedicoNomeParcial(Controle.Referencias.getMedicoLogado(), "");
        atualizaLista(lista);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setToolTipText("");
        setAutoscrolls(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fecharbutton.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel2.setText("Pesquisar:");

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        list1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list1ItemStateChanged(evt);
            }
        });
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        list1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                list1KeyPressed(evt);
            }
        });

        jLabel1.setText("Selecione um paciente para visualizar sua ficha medica:");

        jButton1.setText("Novo Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                        .addGap(133, 133, 133))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(676, 676, 676))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed

    }//GEN-LAST:event_list1ActionPerformed

    private void list1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list1ItemStateChanged
    }//GEN-LAST:event_list1ItemStateChanged

    private void list1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list1KeyPressed
    }//GEN-LAST:event_list1KeyPressed

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        String item = list1.getSelectedItem();
        int codigo = pegaCodigo(item);
        PacienteDAO dao = new PacienteDAO();
        Paciente paciente = dao.selectCodigo(codigo);
        ReferenciasSimilaridade.setPaciente(paciente);
        JanelaCasoFichaMedica janelaNova = new JanelaCasoFichaMedica();
        janelaNova.setName(paciente.getNome());       
        
        JanelaPrincipal.getInstance().jTabbedPaneHome.add(janelaNova);
        JanelaPrincipal.getInstance().jTabbedPaneHome.setSelectedComponent(janelaNova);
    }//GEN-LAST:event_list1MouseClicked
    
    private int pegaCodigo(String item){
        Scanner scanner = new Scanner(item);
        scanner.useDelimiter("-");
        String stringCodigo  = scanner.next();
        int codigo = Integer.parseInt(stringCodigo);
        return codigo;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String NomeParcial = jTextField1.getText();
        PacienteDAO dao = new PacienteDAO();
        ArrayList<Paciente> lista = dao.selectMedicoNomeParcial(Controle.Referencias.getMedicoLogado(), NomeParcial);
        atualizaLista(lista);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JanelaCadastroPaciente jcp = new JanelaCadastroPaciente();
        jcp.setName("Cadastro Paciente");
        jcp.jPanel1.setSize(JanelaPrincipal.getInstance().jTabbedPaneHome.getSize());
        jcp.jScrollPane1.setSize(JanelaPrincipal.getInstance().jTabbedPaneHome.getSize());

//        jcp.jButton1.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (Controle.Validacao.verificaRG(jcp.getRG())) {
//                    if ((jcp.getNome()).equals("") == false && jcp.getRG().equals("") == false && jcp.getCPF() != 0
//                            && jcp.getDataNasc() != null && jcp.getSexo().equals("") == false
//                            && jcp.getTel() != 0 && jcp.getCel() != 0 && jcp.getEndereco().equals("") == false
//                            && jcp.getEndComplemento().equals("") == false && jcp.getCidade().equals("") == false
//                            && jcp.getEstado().equals("") == false && jcp.getEstadoCivil().equals("") == false
//                            && jcp.getTipoSanguineo().equals("") == false) {
//
//                        FichaMedica fm = new FichaMedica(0, jcp.getSexo(), jcp.getTipoSanguineo());
//                        Paciente pac = new Paciente(0, jcp.getCPF(), jcp.getTel(), jcp.getCel(), jcp.getNome(), jcp.getRG(),
//                                jcp.getEndereco(), jcp.getEndComplemento(), jcp.getCidade(), jcp.getEstado(),
//                                jcp.getEstadoCivil(), jcp.getDataNasc(), fm);
//                        PacienteDAO pdao = new PacienteDAO();
//                        pdao.incluir(pac);
//
//                        JOptionPane.showMessageDialog(
//                                null, "Cadastro realizado com sucesso.",
//                                "Confirmação", JOptionPane.PLAIN_MESSAGE);
//                    } else {
//                        JOptionPane.showMessageDialog(
//                                null, "Favor preencher todos os campos.",
//                                "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(
//                            null, "Favor inserir um RG válido.",
//                            "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        });

        JanelaPrincipal.getInstance().jTabbedPaneHome.add(jcp);
        JanelaPrincipal.getInstance().jTabbedPaneHome.setSelectedComponent(jcp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atualizaLista(ArrayList<Paciente> lista) {
        list1.removeAll();
        Iterator iterator = lista.iterator();
        while (iterator.hasNext()) {
            Paciente paciente = (Paciente) iterator.next();
            String nome = paciente.getNome();
            int codigo = paciente.getCodigo();
            
            String item =  codigo+  "- Nome: " + nome;
            list1.add(item);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
