/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaCasoInsereSintomas.java
 *
 * Created on 06/11/2011, 22:37:48
 */
package janelasConsultaSimilaridade;

import ProcessosBD.Caso;
import ProcessosBD.Paciente;
import ProcessosBD.Sintoma;
import DAO.SintomaDAO;
import ProcessosBD.SintomaPeso;
import janelasdoprojetao.Cadastro.JanelaCadastroSintoma;
import janelasdoprojetao.JanelaPrincipal;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernanda
 */
public class JanelaCasoInsereSintomas extends javax.swing.JPanel {

    private ArrayList<String> sintomasNaLista;
    private Caso caso;
    private Paciente paciente;

    public JanelaCasoInsereSintomas(Caso caso, Paciente paciente) {
        this.setName("Escolha de Sintomas");

        this.caso = caso;
        this.paciente = paciente;
        initComponents();
        if (ReferenciasSimilaridade.getSintomasNaLista() != null) {
            this.sintomasNaLista = ReferenciasSimilaridade.getSintomasNaLista();
            colocaSintomasNaLista(sintomasNaLista);
        } else {
            this.sintomasNaLista = new ArrayList<String>();
        }
        labelPaciente.setText("diagnoscando: " + paciente.getNome());
        SintomaDAO dao = new SintomaDAO();
        ArrayList<Sintoma> lista = dao.selectNomeParcial(jTextField1.getText());
        atualizaLista(lista);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        list2 = new java.awt.List();
        list1 = new java.awt.List();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelPaciente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fecharbutton.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Sintomas do Paciente:");

        list2.setMultipleMode(true);
        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        list2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list2ItemStateChanged(evt);
            }
        });
        list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2ActionPerformed(evt);
            }
        });
        list2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                list2KeyPressed(evt);
            }
        });

        list1.setMultipleMode(true);

        jButton3.setActionCommand("jButton3");
        jButton3.setLabel("Adicionar >");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton6.setText("Buscar Diagnósticos >>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Digite o nome do sintoma para pesquisa");

        labelPaciente.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelPaciente.setText("Adicione os sintomas do seu paciente");

        jButton1.setText("Novo Sintoma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("<< Voltar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPaciente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelPaciente)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton3)
                        .addGap(95, 95, 95)
                        .addComponent(jButton4))
                    .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton1)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // QUANDO PRESSIONA ENTER NO TEXTBOX!
        // COPIAR CODIGO DE BAIXO. =)
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ReferenciasSimilaridade.limpaReferencias();
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);
}//GEN-LAST:event_jButton2ActionPerformed

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_list2MouseClicked

    private void list2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list2ItemStateChanged

    private void list2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list2ActionPerformed

    private void list2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_list2KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Adicionar >

        String[] adc = list1.getSelectedItems();

        for (String s : adc) {
            list2.add(s);
            list1.remove(s);
            sintomasNaLista.add(s);
        }


    }//GEN-LAST:event_jButton3ActionPerformed
    private void colocaSintomasNaLista(ArrayList<String> sintomas) {
        for (String sintoma : sintomas) {
            list2.add(sintoma);
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // < Remover

        String[] rem = list2.getSelectedItems();

        for (String r : rem) {
            list1.add(r);
            list2.remove(r);
            sintomasNaLista.remove(r);
        }

    }//GEN-LAST:event_jButton4ActionPerformed
    public void atualizaLista(ArrayList<Sintoma> sintomas) {
        list1.removeAll();
        Iterator iterator = sintomas.iterator();
        while (iterator.hasNext()) {
            Sintoma sintoma = (Sintoma) iterator.next();
            String nomeSintoma = sintoma.getNome();
            if (!sintomasNaLista.contains(nomeSintoma)) {
                list1.add(nomeSintoma);
            }

        }

    }

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        SintomaDAO dao = new SintomaDAO();
        ArrayList<Sintoma> lista = dao.selectNomeParcial(jTextField1.getText());
        atualizaLista(lista);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ReferenciasSimilaridade.setSintomasNaLista(sintomasNaLista);

        String[] sintomas = list2.getItems();
        ArrayList<SintomaPeso> sintomasCaso = new ArrayList<SintomaPeso>();
        SintomaDAO dao = new SintomaDAO();
        for (String s : sintomas) {
            Sintoma sintoma = dao.selectNome(s);
            SintomaPeso sintomaPeso = new SintomaPeso(sintoma, null, 0);
            sintomasCaso.add(sintomaPeso);
        }
        this.caso.setSintomas(sintomasCaso);
        JanelaEscolheDoenca janela = new JanelaEscolheDoenca(caso, paciente);
        janela.setName("Confirmação do Diagnostico");
        JanelaPrincipal.getInstance().jTabbedPaneHome.add(janela);
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        janelasdoprojetao.Cadastro.JanelaCadastroSintoma cs = new JanelaCadastroSintoma();
        cs.setName("Cadastro Sintoma");
        JanelaPrincipal.getInstance().jTabbedPaneHome.add(cs);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ReferenciasSimilaridade.setSintomasNaLista(sintomasNaLista);
        JanelaCasoFichaMedica janelaNova = new JanelaCasoFichaMedica();
        janelaNova.setName(paciente.getNome());
        JanelaPrincipal.getInstance().jTabbedPaneHome.add(janelaNova);
        JanelaPrincipal.getInstance().jTabbedPaneHome.setSelectedComponent(janelaNova);
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);


    }//GEN-LAST:event_jButton5ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelPaciente;
    private java.awt.List list1;
    protected java.awt.List list2;
    // End of variables declaration//GEN-END:variables
}
