/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaEscolheDoenca.java
 *
 * Created on 24/11/2011, 00:30:45
 */
package janelasConsultaSimilaridade;

import DAO.SintomaDAO;
import DAO.DoencaDAO;
import DAO.CasoDAO;
import janelasdepesquisas.JanelaMostraDoenca;
import EquacaoSimilaridade.CasoSimilar;
import EquacaoSimilaridade.EquacaoBD;
import ProcessosBD.*;
import janelasdoprojetao.JanelaPrincipal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Controle.MetodosUteis;

/**
 *
 * @author Gabriel
 */
public class JanelaEscolheDoenca extends javax.swing.JPanel {

    /** Creates new form JanelaEscolheDoenca */
    private Caso caso;
    private Paciente paciente;
    private Doenca outraDoencaSelecionada;

    public JanelaEscolheDoenca(Caso caso, Paciente paciente) {
        ArrayList<CasoSimilar> casos = EquacaoBD.BuscaSimilares(caso, 20);
        initComponents();
        atualizaLista(casos);

        this.paciente = paciente;
        this.caso = caso;
    }

    private void atualizaCaso(Caso caso) {
    }

    private void atualizaLista(ArrayList<CasoSimilar> casos) {
        list1.removeAll();
        for (CasoSimilar caso : casos) {
            String nomeDoenca = null;
            int codCaso;
            DoencaDAO dao = new DoencaDAO();
            Doenca doenca = dao.selectCodigo(caso.getDoenca().getCodigo());
            caso.setDoenca(doenca);
            nomeDoenca = caso.getDoenca().getNome();
            codCaso = caso.getCodigo();
            String item = codCaso + " - " + nomeDoenca + " - " + MetodosUteis.truncaDouble(caso.getSimilaridade(), 2) + '%';
            list1.add(item);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        labelIdade = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        labelAltura1 = new javax.swing.JLabel();
        labelAltura2 = new javax.swing.JLabel();
        list2 = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelAltura3 = new javax.swing.JLabel();
        list3 = new java.awt.List();
        jButton4 = new javax.swing.JButton();
        checkboxDoenca = new java.awt.Checkbox();

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fecharbutton.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnConfirmar.setText("Escolher como diagnóstico");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Selecione um diagnóstico na lista:");

        list1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list1ItemStateChanged(evt);
            }
        });
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        labelIdade.setText("Idade:");

        labelPeso.setText("Peso:");

        labelAltura.setText("Altura:");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        jTextField3.setEditable(false);

        jLabel1.setText("Código do caso - Nome da doença - Porcentagem de similaridade");

        jTextField4.setEditable(false);

        labelAltura1.setText("Remedios Frequentes:");

        labelAltura2.setText("Sintomas em Comum:");

        jButton1.setText("Ver detalhes da doença");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Outra Doença");
        jButton3.setLabel("Selecionar outra doença >>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        labelAltura3.setText("Outros sintomas:");

        list3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list3ItemStateChanged(evt);
            }
        });
        list3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list3ActionPerformed(evt);
            }
        });

        jButton4.setText("<< Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        checkboxDoenca.setEnabled(false);
        checkboxDoenca.setLabel("Outra Doença Selecionada : Nenhuma");
        checkboxDoenca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxDoencaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(checkboxDoenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelAltura2)
                                            .addComponent(labelAltura3))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(list2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(list3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelIdade)
                                            .addComponent(labelPeso)
                                            .addComponent(labelAltura)
                                            .addComponent(labelAltura1))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))))
                            .addComponent(jLabel1))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)))
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(labelAltura2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(labelIdade)
                                        .addGap(15, 15, 15)
                                        .addComponent(labelPeso)
                                        .addGap(15, 15, 15)
                                        .addComponent(labelAltura)
                                        .addGap(12, 12, 12)
                                        .addComponent(labelAltura1)))
                                .addGap(25, 25, 25)
                                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAltura3))))
                .addGap(4, 4, 4)
                .addComponent(checkboxDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(btnConfirmar))
                .addContainerGap())
        );

        labelAltura1.getAccessibleContext().setAccessibleName("label1");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ReferenciasSimilaridade.limpaReferencias();
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);
}//GEN-LAST:event_jButton2ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (!checkboxDoenca.getState()) {
            String selecionado = list1.getSelectedItem();
            String codigo = selecionado.split(" - ")[0];
            CasoDAO casodao = new CasoDAO();
            Caso ocaso = casodao.selectPorCodigo(Integer.parseInt(codigo));
            int codigodoenca = ocaso.getDoenca().getCodigo();
            DoencaDAO doencadao = new DoencaDAO();
            Doenca doe = doencadao.selectPorCodigo(codigodoenca);

            caso.setDoenca(doe);
        }else{
            caso.setDoenca(outraDoencaSelecionada);
        }
        String[] sintomas = list2.getItems();
        ArrayList<SintomaPeso> sintomasCaso = new ArrayList<SintomaPeso>();
        SintomaDAO dao = new SintomaDAO();
        for (String s : sintomas) {
            Sintoma sintoma = dao.selectNome(s);
            SintomaPeso sintomaPeso = new SintomaPeso(sintoma, caso.getDoenca(), 0);
            sintomasCaso.add(sintomaPeso);
        }
        caso.setSintomas(sintomasCaso);

        EquacaoBD.gravaCasoBD(caso);
        JOptionPane.showConfirmDialog(null, "Caso gravado no Banco com Sucesso");
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void list1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list1ItemStateChanged
        String selecionado = list1.getSelectedItem();
        String codigo = selecionado.split(" - ")[0];

        CasoDAO casodao = new CasoDAO();
        Caso codCaso = casodao.selectPorCodigo(Integer.parseInt(codigo));

        jTextField1.setText(Integer.toString(codCaso.getIdade()));
        jTextField2.setText(Float.toString(codCaso.getPeso()));
        jTextField3.setText(Float.toString(codCaso.getAltura()));
        jTextField4.setText(codCaso.getMedicacoes());

        list2.removeAll();
        list3.removeAll();
        Caso caso1 = this.caso;
        for (SintomaPeso p : codCaso.getSintomas()) {
            if (caso1.getSintomas().contains(p)) {
                list2.add(p.getSintoma().getNome());
            } else if (!caso1.getSintomas().contains(p)) {
                list3.add(p.getSintoma().getNome());
            }
        }


    }//GEN-LAST:event_list1ItemStateChanged

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
    }//GEN-LAST:event_list1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Detalhes sobre a doença

        if (list1.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma doença da lista.",
                    "ATENÇÃO", JOptionPane.PLAIN_MESSAGE);
        } else {

            String selecionado = list1.getSelectedItem();
            String codigo = selecionado.split(" - ")[0];
            CasoDAO casodao = new CasoDAO();
            Caso ocaso = casodao.selectPorCodigo(Integer.parseInt(codigo));
            int codigodoenca = ocaso.getDoenca().getCodigo();
            DoencaDAO doencadao = new DoencaDAO();
            Doenca doe = doencadao.selectPorCodigo(codigodoenca);

            JanelaMostraDoenca jcd = new JanelaMostraDoenca(doe);
            jcd.setName("Doença: " + doe.getNome());

            JanelaPrincipal.getInstance().jTabbedPaneHome.add(jcd);
            JanelaPrincipal.getInstance().jTabbedPaneHome.setSelectedComponent(jcd);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Doenca doenca = JDoencaChooser.getDoenca();
        outraDoencaSelecionada = doenca;
        checkboxDoenca.setLabel("Outra Doença Selecionada : " + doenca.getNome());
        checkboxDoenca.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Voltar
        JanelaCasoInsereSintomas janelaNova = new JanelaCasoInsereSintomas(caso, paciente);
        JanelaPrincipal.getInstance().jTabbedPaneHome.add(janelaNova);
        JanelaPrincipal.getInstance().jTabbedPaneHome.setSelectedComponent(janelaNova);
        JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void list3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list3ItemStateChanged
        if (list1.getSelectedItem() != null) {
            String sintoma = list3.getSelectedItem();
            Object[] options = {"Sim", "Não"};
            int n = JOptionPane.showOptionDialog(this,
                    "O paciente está com " + sintoma + "?",
                    "Adicionar um sintoma",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);

            if (n == JOptionPane.YES_OPTION) {

                //ADICIONAR UM SINTOMA AO CASO
                String selecionado = list3.getSelectedItem();
                String sintomaNome = selecionado.toString();

                SintomaDAO sintDAO = new SintomaDAO();
                Sintoma sint = sintDAO.selectNome(sintomaNome);
                SintomaPeso sintomaPeso = new SintomaPeso(sint, null, 0);
                this.caso.getSintomas().add(sintomaPeso);
                list3.remove(selecionado);
                list2.add(selecionado);
                ReferenciasSimilaridade.getSintomasNaLista().add(selecionado);
                JanelaEscolheDoenca janelaNova = new JanelaEscolheDoenca(caso, paciente);
                JanelaPrincipal.getInstance().jTabbedPaneHome.add(janelaNova);
                JanelaPrincipal.getInstance().jTabbedPaneHome.remove(this);




            }
        }

    }//GEN-LAST:event_list3ItemStateChanged

    private void list3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list3ActionPerformed

    private void checkboxDoencaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxDoencaItemStateChanged
        list1.select(-1);
    }//GEN-LAST:event_checkboxDoencaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private java.awt.Checkbox checkboxDoenca;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelAltura1;
    private javax.swing.JLabel labelAltura2;
    private javax.swing.JLabel labelAltura3;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelPeso;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.List list3;
    // End of variables declaration//GEN-END:variables
}
